//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPolApplication.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasterPolBDEntities : DbContext
    {


        private static MasterPolBDEntities _context;

        public static MasterPolBDEntities GetContext()
        {
            if (_context == null)
            {
                _context = new MasterPolBDEntities();
            }
            return _context;
        }

        public MasterPolBDEntities()
            : base("name=MasterPolBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adress> Adress { get; set; }
        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<Cityes> Cityes { get; set; }
        public virtual DbSet<Directors> Directors { get; set; }
        public virtual DbSet<Indexes> Indexes { get; set; }
        public virtual DbSet<MaterialType> MaterialType { get; set; }
        public virtual DbSet<PartnerProducts> PartnerProducts { get; set; }
        public virtual DbSet<Partners> Partners { get; set; }
        public virtual DbSet<PartnerTypes> PartnerTypes { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductType> ProductType { get; set; }
        public virtual DbSet<Streets> Streets { get; set; }
    }
}
